package com.ikoko.top.word.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ikoko.top.word.entity.IcibaSentence;
import com.ikoko.top.word.entity.IcibaSentenceExample;

public interface IcibaSentenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int countByExample(IcibaSentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int deleteByExample(IcibaSentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int insert(IcibaSentence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int insertSelective(IcibaSentence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    List<IcibaSentence> selectByExample(IcibaSentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    IcibaSentence selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") IcibaSentence record, @Param("example") IcibaSentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int updateByExample(@Param("record") IcibaSentence record, @Param("example") IcibaSentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int updateByPrimaryKeySelective(IcibaSentence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iciba_sentence
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    int updateByPrimaryKey(IcibaSentence record);
}