package com.ikoko.top.word.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ikoko.top.word.entity.SentenceWordRel;
import com.ikoko.top.word.entity.SentenceWordRelExample;

public interface SentenceWordRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int countByExample(SentenceWordRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int deleteByExample(SentenceWordRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int insert(SentenceWordRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int insertSelective(SentenceWordRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    List<SentenceWordRel> selectByExample(SentenceWordRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    SentenceWordRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") SentenceWordRel record, @Param("example") SentenceWordRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int updateByExample(@Param("record") SentenceWordRel record, @Param("example") SentenceWordRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int updateByPrimaryKeySelective(SentenceWordRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence_word_rel
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    int updateByPrimaryKey(SentenceWordRel record);
}