package com.ikoko.top.word.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ikoko.top.word.entity.Sentence;
import com.ikoko.top.word.entity.SentenceExample;

public interface SentenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int countByExample(SentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int deleteByExample(SentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int insert(Sentence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int insertSelective(Sentence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    List<Sentence> selectByExample(SentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    Sentence selectByPrimaryKey(Long id);
    
    List<Sentence> selectByArticle(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") Sentence record, @Param("example") SentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int updateByExample(@Param("record") Sentence record, @Param("example") SentenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int updateByPrimaryKeySelective(Sentence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sentence
     *
     * @mbggenerated Thu Dec 01 11:13:40 CST 2016
     */
    int updateByPrimaryKey(Sentence record);
}