package com.ikoko.top.word.entity;

public class Acceptation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acceptation.id
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acceptation.word_id
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    private Long wordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acceptation.pos
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    private String pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acceptation.acceptation
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    private String acceptation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acceptation.id
     *
     * @return the value of acceptation.id
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acceptation.id
     *
     * @param id the value for acceptation.id
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acceptation.word_id
     *
     * @return the value of acceptation.word_id
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public Long getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acceptation.word_id
     *
     * @param wordId the value for acceptation.word_id
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acceptation.pos
     *
     * @return the value of acceptation.pos
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acceptation.pos
     *
     * @param pos the value for acceptation.pos
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public void setPos(String pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acceptation.acceptation
     *
     * @return the value of acceptation.acceptation
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public String getAcceptation() {
        return acceptation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acceptation.acceptation
     *
     * @param acceptation the value for acceptation.acceptation
     *
     * @mbggenerated Thu Dec 01 18:25:16 CST 2016
     */
    public void setAcceptation(String acceptation) {
        this.acceptation = acceptation;
    }
}