package com.ikoko.top.word.entity;

public class IcibaSentence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iciba_sentence.id
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iciba_sentence.word_id
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    private Long wordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iciba_sentence.orig
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    private String orig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iciba_sentence.trans
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    private String trans;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iciba_sentence.id
     *
     * @return the value of iciba_sentence.id
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iciba_sentence.id
     *
     * @param id the value for iciba_sentence.id
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iciba_sentence.word_id
     *
     * @return the value of iciba_sentence.word_id
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public Long getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iciba_sentence.word_id
     *
     * @param wordId the value for iciba_sentence.word_id
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iciba_sentence.orig
     *
     * @return the value of iciba_sentence.orig
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public String getOrig() {
        return orig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iciba_sentence.orig
     *
     * @param orig the value for iciba_sentence.orig
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public void setOrig(String orig) {
        this.orig = orig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iciba_sentence.trans
     *
     * @return the value of iciba_sentence.trans
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public String getTrans() {
        return trans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iciba_sentence.trans
     *
     * @param trans the value for iciba_sentence.trans
     *
     * @mbggenerated Thu Dec 01 18:28:10 CST 2016
     */
    public void setTrans(String trans) {
        this.trans = trans;
    }
}