package com.ikoko.top.word.entity;

public class SentenceWordRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_word_rel.id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_word_rel.sentence_id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    private Long sentenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_word_rel.word_id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    private Long wordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_word_rel.id
     *
     * @return the value of sentence_word_rel.id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_word_rel.id
     *
     * @param id the value for sentence_word_rel.id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_word_rel.sentence_id
     *
     * @return the value of sentence_word_rel.sentence_id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    public Long getSentenceId() {
        return sentenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_word_rel.sentence_id
     *
     * @param sentenceId the value for sentence_word_rel.sentence_id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    public void setSentenceId(Long sentenceId) {
        this.sentenceId = sentenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_word_rel.word_id
     *
     * @return the value of sentence_word_rel.word_id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    public Long getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_word_rel.word_id
     *
     * @param wordId the value for sentence_word_rel.word_id
     *
     * @mbggenerated Thu Dec 01 11:16:45 CST 2016
     */
    public void setWordId(Long wordId) {
        this.wordId = wordId;
    }
}