package com.ikoko.top.word.entity;

import java.util.ArrayList;
import java.util.List;

public class Word {
    private Long id;
    private String wordName;
    private String phAm;
    private String exchange;
    private String parts;
    private byte[] phAmMp3;
    private List<Acceptation> acceptations = new ArrayList<Acceptation>(); 


    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.id
     *
     * @param id the value for word.id
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.word_name
     *
     * @return the value of word.word_name
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public String getWordName() {
        return wordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.word_name
     *
     * @param wordName the value for word.word_name
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setWordName(String wordName) {
        this.wordName = wordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.ph_am
     *
     * @return the value of word.ph_am
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public String getPhAm() {
        return phAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.ph_am
     *
     * @param phAm the value for word.ph_am
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setPhAm(String phAm) {
        this.phAm = phAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.exchange
     *
     * @return the value of word.exchange
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.exchange
     *
     * @param exchange the value for word.exchange
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.parts
     *
     * @return the value of word.parts
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public String getParts() {
        return parts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.parts
     *
     * @param parts the value for word.parts
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setParts(String parts) {
        this.parts = parts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.ph_am_mp3
     *
     * @return the value of word.ph_am_mp3
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public byte[] getPhAmMp3() {
        return phAmMp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.ph_am_mp3
     *
     * @param phAmMp3 the value for word.ph_am_mp3
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setPhAmMp3(byte[] phAmMp3) {
        this.phAmMp3 = phAmMp3;
    }

    public List<Acceptation> getAcceptations() {
        return acceptations;
    }

    public void setAcceptations(List<Acceptation> acceptations) {
        this.acceptations = acceptations;
    }
    
}