package com.ikoko.top.word.entity;

import java.util.ArrayList;
import java.util.List;

public class WordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public WordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWordNameIsNull() {
            addCriterion("word_name is null");
            return (Criteria) this;
        }

        public Criteria andWordNameIsNotNull() {
            addCriterion("word_name is not null");
            return (Criteria) this;
        }

        public Criteria andWordNameEqualTo(String value) {
            addCriterion("word_name =", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameNotEqualTo(String value) {
            addCriterion("word_name <>", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameGreaterThan(String value) {
            addCriterion("word_name >", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameGreaterThanOrEqualTo(String value) {
            addCriterion("word_name >=", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameLessThan(String value) {
            addCriterion("word_name <", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameLessThanOrEqualTo(String value) {
            addCriterion("word_name <=", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameLike(String value) {
            addCriterion("word_name like", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameNotLike(String value) {
            addCriterion("word_name not like", value, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameIn(List<String> values) {
            addCriterion("word_name in", values, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameNotIn(List<String> values) {
            addCriterion("word_name not in", values, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameBetween(String value1, String value2) {
            addCriterion("word_name between", value1, value2, "wordName");
            return (Criteria) this;
        }

        public Criteria andWordNameNotBetween(String value1, String value2) {
            addCriterion("word_name not between", value1, value2, "wordName");
            return (Criteria) this;
        }

        public Criteria andPhAmIsNull() {
            addCriterion("ph_am is null");
            return (Criteria) this;
        }

        public Criteria andPhAmIsNotNull() {
            addCriterion("ph_am is not null");
            return (Criteria) this;
        }

        public Criteria andPhAmEqualTo(String value) {
            addCriterion("ph_am =", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmNotEqualTo(String value) {
            addCriterion("ph_am <>", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmGreaterThan(String value) {
            addCriterion("ph_am >", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmGreaterThanOrEqualTo(String value) {
            addCriterion("ph_am >=", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmLessThan(String value) {
            addCriterion("ph_am <", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmLessThanOrEqualTo(String value) {
            addCriterion("ph_am <=", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmLike(String value) {
            addCriterion("ph_am like", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmNotLike(String value) {
            addCriterion("ph_am not like", value, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmIn(List<String> values) {
            addCriterion("ph_am in", values, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmNotIn(List<String> values) {
            addCriterion("ph_am not in", values, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmBetween(String value1, String value2) {
            addCriterion("ph_am between", value1, value2, "phAm");
            return (Criteria) this;
        }

        public Criteria andPhAmNotBetween(String value1, String value2) {
            addCriterion("ph_am not between", value1, value2, "phAm");
            return (Criteria) this;
        }

        public Criteria andExchangeIsNull() {
            addCriterion("exchange is null");
            return (Criteria) this;
        }

        public Criteria andExchangeIsNotNull() {
            addCriterion("exchange is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeEqualTo(String value) {
            addCriterion("exchange =", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeNotEqualTo(String value) {
            addCriterion("exchange <>", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeGreaterThan(String value) {
            addCriterion("exchange >", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeGreaterThanOrEqualTo(String value) {
            addCriterion("exchange >=", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeLessThan(String value) {
            addCriterion("exchange <", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeLessThanOrEqualTo(String value) {
            addCriterion("exchange <=", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeLike(String value) {
            addCriterion("exchange like", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeNotLike(String value) {
            addCriterion("exchange not like", value, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeIn(List<String> values) {
            addCriterion("exchange in", values, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeNotIn(List<String> values) {
            addCriterion("exchange not in", values, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeBetween(String value1, String value2) {
            addCriterion("exchange between", value1, value2, "exchange");
            return (Criteria) this;
        }

        public Criteria andExchangeNotBetween(String value1, String value2) {
            addCriterion("exchange not between", value1, value2, "exchange");
            return (Criteria) this;
        }

        public Criteria andPartsIsNull() {
            addCriterion("parts is null");
            return (Criteria) this;
        }

        public Criteria andPartsIsNotNull() {
            addCriterion("parts is not null");
            return (Criteria) this;
        }

        public Criteria andPartsEqualTo(String value) {
            addCriterion("parts =", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsNotEqualTo(String value) {
            addCriterion("parts <>", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsGreaterThan(String value) {
            addCriterion("parts >", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsGreaterThanOrEqualTo(String value) {
            addCriterion("parts >=", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsLessThan(String value) {
            addCriterion("parts <", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsLessThanOrEqualTo(String value) {
            addCriterion("parts <=", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsLike(String value) {
            addCriterion("parts like", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsNotLike(String value) {
            addCriterion("parts not like", value, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsIn(List<String> values) {
            addCriterion("parts in", values, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsNotIn(List<String> values) {
            addCriterion("parts not in", values, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsBetween(String value1, String value2) {
            addCriterion("parts between", value1, value2, "parts");
            return (Criteria) this;
        }

        public Criteria andPartsNotBetween(String value1, String value2) {
            addCriterion("parts not between", value1, value2, "parts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 01 11:14:43 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word
     *
     * @mbggenerated Thu Dec 01 11:14:43 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}